import { BrowserRouter as Router, Switch, Route } from 'react-router-dom'
import styled from 'styled-components'
import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import ChatRoom from '../components/ChatRoom'
import HomeChat from '../components/HomeChat'

export default function Home() {
  return (
    <div>
      <Head>
        <title>React Whatsapp clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Main>
        <Router>
          <Container>
            <Sidebar />
            <Switch>
              <ChatContainer>
                <Route exact path='/'>
                  <HomeChat />
                </Route>
                <Route exact path='/chat/:id'>
                  <ChatRoom />
                </Route>
              </ChatContainer>
            </Switch>
          </Container>
        </Router>
      </Main>
    </div>
  )
}

const Main = styled.div`
  width: 100vw;
  height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #d8dbd5;

  ::after {
    width: 100%;
    height: calc(2vh + 143px);
    position: fixed;
    top: 0;
    content: '';
    background-color: #009688;
    box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.06), 0 2px 5px 0 rgba(0, 0, 0, 0.2);
  }

  ::-webkit-scrollbar {
    width: 6px;
    height: 6px;
    background-color: #f5f5f5;
  }

  ::-webkit-scrollbar-thumb {
    background-color: rgba(0, 0, 0, 0.2);
  }

  ::-webkit-scrollbar-track {
    background-color: rgba(255, 255, 255, 0.08);
  }

  @media only screen and (max-width: 900px) {
    max-width: 900px;
    overflow-x: scroll;

    section {
      width: 900px;
    }
  }

  @media only screen and (max-height: 512px) {
    overflow-y: auto;
  }
`

const Container = styled.div`
  width: 100vw;
  height: 100vh;
  z-index: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #f7f7f7;

  .MuiDrawer-root {
    width: 350px;
    height: 100%;

    .MuiDrawer-paper {
      top: auto;
    }
  }

  @media only screen and (min-width: 1441px) {
    width: 75vw;
    height: 96vh;
    margin: 0 auto;
    box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.06), 0 2px 5px 0 rgba(0, 0, 0, 0.2);

    .MuiDrawer-root {
      .MuiPaper-root {
        height: 96vh;
      }
    }

    .MuiDrawer-paperAnchorLeft {
      left: auto;
    }
  }
`

const ChatContainer = styled.div`
  width: calc(100vw - 350px);
  height: 100%;
  flex: 1;
`
